VALIDATOR_LIST:
  - node0:
      host: node0.rchain.coop
      grpc_port: 40401
      http_port: 40403
      pub_key: key1
DB_PATH:
  /path/to/database
TARGET_RNODE_HOST:
  rnode.host
TARGET_RNODE_PORT:
  40401
TARGET_RNODE_HTTP_PORT:
  40403
USE_HTTPS:
  false
HOST:
  0.0.0.0
PORT:
  7070
NUM_CORE:
  4
LOG_PATH:
  /path/to/log.log
MAX_MEM:
  500048576
CACHE_TTL:
  60